#!/bin/sh

# $FreeBSD: head/audio/supybot/files/supybot.in 340851 2014-01-23 19:55:14Z mat $
#
# PROVIDE: supybot
# REQUIRE: NETWORKING icecast2 shoutcast
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable supybot:
#
# supybot_enable="YES"
#

. /etc/rc.subr

name=supybot
rcvar=supybot_enable

command=/usr/local/bin/supybot

load_rc_config $name

: ${supybot_enable:="NO"}
: ${supybot_pidfile:="/var/run/supybot/supybot.pid"}
: ${supybot_config:="/usr/local/etc/supybot/supybot.conf"}
: ${supybot_user:="supybot"}
: ${supybot_group:="supybot"}

pidfile="${supybot_pidfile}"
required_files="${supybot_config}"

supybot_stop()
{
    local pid

    pid=$(check_pidfile ${supybot_pidfile} /usr/local/bin/supybot /usr/local/bin/python2.7)
    if [ -z ${pid} ]
    then
	    warn "not running"
	    return 1 
    fi
    echo "Found $pid killing...."

    kill $pid
    wait_for_pids $pid >/dev/null
}
stop_cmd="${name}_stop"

supybot_prestart()
{
    command_args="-d ${supybot_config}"
    if ! [ -z $(check_pidfile ${supybot_pidfile} /usr/local/bin/supybot /usr/local/bin/python2.7) ]
    then
	    warn "Already running"
	    return 1 
    fi
    return 0
}
start_precmd="${name}_prestart"

supybot_status()
{
    if ! [ -z $(check_pidfile ${supybot_pidfile} /usr/local/bin/supybot /usr/local/bin/python2.7) ]
    then
        echo 'OK'
	return 0
    fi
    echo 'NOT running'
    return 1 
}
status_cmd="${name}_status"
run_rc_command "$1"
