#!/usr/local/bin/python2

import sys
import os
import re
import json
import subprocess

plugin_path = os.path.dirname(os.path.realpath(__file__))
data = sys.argv[1]
data = re.sub("'", '"', data)
data = re.sub("True", '"TRUE"', data)
data = re.sub("False", '"FALSE"', data)
data = json.loads(data)
name = data.keys()[0]
plugin_data = data[name]
if (os.path.isdir('{}/{}/.git'.format(plugin_path, name))):
    subprocess.call(["git", "fetch", "origin"])
    subprocess.call(["git", "pull", "--ff-only"])
elif 'repo' in data[name]:
    repo = data[name]['repo']
    subprocess.call(["git", "clone", repo, '{}/{}'.format(plugin_path, name)])
